services:
  nav3d:
    image: nav3d-img
    privileged: true
    network_mode: host
    ipc: host
    environment:
      DISPLAY: ${DISPLAY:-:0}
      XAUTHORITY: /tmp/.docker.xauth
      QT_X11_NO_MITSHM: "1"
      RMW_IMPLEMENTATION: rmw_cyclonedds_cpp
    volumes:
      - ..:/workspaces/nav3d_sim:cached
      - /tmp/.X11-unix:/tmp/.X11-unix:ro
      - ./.docker.xauth:/tmp/.docker.xauth:ro
      - /dev:/dev
    command: sleep infinity
