#!/usr/bin/env bash
set -euo pipefail

gpu_repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
gpu_xauth_path="${gpu_repo_root}/.devcontainer/.docker.xauth"
gpu_override_path="${gpu_repo_root}/.devcontainer/docker-compose.gpu.generated.yml"
gpu_override_tmp="$(mktemp "${gpu_override_path}.tmp.XXXXXX")"

# Keep the bind mount at the same host path and inode across desktop sessions.
# GNOME's XAUTHORITY path can change while Docker still has an older container.
umask 077
if [[ -L "${gpu_xauth_path}" || ( -e "${gpu_xauth_path}" && ! -f "${gpu_xauth_path}" ) ]]; then
  echo "Expected a regular Xauthority file at ${gpu_xauth_path}" >&2
  exit 1
fi
: >> "${gpu_xauth_path}"
chmod 600 "${gpu_xauth_path}"

gpu_xauth_source="${XAUTHORITY:-${HOME}/.Xauthority}"
if [[ -f "${gpu_xauth_source}" && "${gpu_xauth_source}" != "${gpu_xauth_path}" ]]; then
  cat -- "${gpu_xauth_source}" > "${gpu_xauth_path}"
elif [[ ! -f "${gpu_xauth_source}" ]]; then
  : > "${gpu_xauth_path}"
  printf 'Xauthority source not found: %s. Graphical X11 applications may not connect.\n' "${gpu_xauth_source}" >&2
fi

cleanup_gpu_override() {
  rm -f "${gpu_override_tmp}"
}
trap cleanup_gpu_override EXIT

write_neutral_override() {
  printf '%s\n' \
    'services:' \
    '  nav3d: {}' \
    > "${gpu_override_tmp}"
}

write_nvidia_override() {
  printf '%s\n' \
    'services:' \
    '  nav3d:' \
    '    gpus: all' \
    '    environment:' \
    '      NVIDIA_VISIBLE_DEVICES: all' \
    '      NVIDIA_DRIVER_CAPABILITIES: all' \
    '      __NV_PRIME_RENDER_OFFLOAD: "1"' \
    '      __GLX_VENDOR_LIBRARY_NAME: nvidia' \
    > "${gpu_override_tmp}"
}

write_neutral_override
gpu_mode="agnostic"

if command -v nvidia-smi >/dev/null 2>&1 && nvidia-smi -L >/dev/null 2>&1; then
  gpu_docker_runtimes="$(docker info --format '{{json .Runtimes}}' 2>/dev/null || true)"
  if grep -q '"nvidia"' <<< "${gpu_docker_runtimes}"; then
    write_nvidia_override
    gpu_mode="nvidia"
  else
    printf '%s\n' \
      'NVIDIA rilevata, ma NVIDIA Container Toolkit non risulta configurato in Docker.' \
      'Il Dev Container proseguira in modalita agnostica.' >&2
  fi
fi

mv -f "${gpu_override_tmp}" "${gpu_override_path}"
trap - EXIT
printf 'Dev Container GPU mode: %s\n' "${gpu_mode}"

bash "${gpu_repo_root}/scripts/bootstrap.sh"

# Compose 5 delegates builds to Bake, which cannot read the temporary Dockerfile
# generated by Dev Containers outside the project without an fs.read entitlement.
# Build the project image directly; Compose only starts the resulting image.
docker build --tag nav3d-img --file "${gpu_repo_root}/docker/Dockerfile" "${gpu_repo_root}"
